version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: admin_key
      MYSQL_USER: adminkey
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    
  web:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: docker-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '81:80'
    links:
      - mysql      