<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Crear' => 'Crear',
    'Mostrar primera página' => 'Mostrar primera pàgina',
    'Mostrar todos los registros' => 'Mostrar tots els registres',
    'Paginados' => 'Paginats',
    'Resetear grid' => 'Resetear grid',
    'Todos' => 'Tots',
    'Copiar' => 'Copiar',
    'General' => 'General',
    'Limpiar filtros' => 'Netejar filtres',
    'Nueva Solicitud' => 'Nova Sol·licitud',
    'Recargar' => 'Recarregar',
    'Recargar manteniendo filtros' => 'Recarregar mantenint filtres',
    'Teléfono' => 'Telèfon',
    'Tipo llamada' => 'Tipus trucada',
    'grid_reset_filter' => 'grid_reset_filter',
    'Buscar dirección' => 'Cerca direcció',
    'Centrar ' => 'Centrar',
    'Cerrar' => 'Tancar',
    'Comprobar' => 'Comprovar',
    'Descargar Carta' => 'Descarregar Carta',
    'Descargar Solicitud' => 'Descarregar Sol·licitud',
    'Descargar excel con todas las solicitudes' => 'Descarregar excel amb totes les sol·licituds',
    'Descargar facturas' => 'Descarregar factures',
    'Editar' => 'Editar',
    'Editar Contrato' => 'Editar Contracte',
    'Eliminar' => 'Eliminar',
    'Eliminar filtros' => 'Eliminar filtres',
    'Enviar' => 'Enviar',
    'Limpiar' => 'Netejar'
];
