<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Crear' => '',
    'Mostrar primera página' => '',
    'Mostrar todos los registros' => '',
    'Paginados' => '',
    'Resetear grid' => '',
    'Todos' => '',
    'Copiar' => '@@@@',
    'General' => '@@@@',
    'Limpiar filtros' => '@@@@',
    'Nueva Solicitud' => '@@@@',
    'Recargar' => '@@@@',
    'Recargar manteniendo filtros' => '@@@@',
    'Teléfono' => '@@@@',
    'Tipo llamada' => '@@@@',
    'grid_reset_filter' => '@@@@',
    'Buscar dirección' => '@@@@',
    'Centrar ' => '@@@@',
    'Cerrar' => '@@@@',
    'Comprobar' => '@@@@',
    'Descargar Carta' => '@@@@',
    'Descargar Solicitud' => '@@@@',
    'Descargar excel con todas las solicitudes' => '@@@@',
    'Descargar facturas' => '@@@@',
    'Editar' => '@@@@',
    'Editar Contrato' => '@@@@',
    'Eliminar' => '@@@@',
    'Eliminar filtros' => '@@@@',
    'Enviar' => '@@@@',
    'Generar Cartas de Solicitud' => '@@@@',
    'Limpiar' => '@@@@',
    'Por DNI / NIF / CIF 💳' => '@@@@',
    'Por nombre y codigo postal 🏡' => '@@@@',
    'Proceder a contratar' => '@@@@',
    'Proceder a reservar' => '@@@@',
    'Ver' => '@@@@',
    'Ver Cartas de Solicitud' => '@@@@',
    'Ver Contrato' => '@@@@',
    'Ver Detalles de Carta' => '@@@@',
    'Ver Organismo' => '@@@@',
    'Ver detalle carta' => '@@@@',
];
