<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Crear' => 'Create',
    'Mostrar primera página' => 'Show first page',
    'Mostrar todos los registros' => 'Show all records',
    'Paginados' => 'Paginated',
    'Resetear grid' => 'Reset grid',
    'Todos' => 'All',
    'Copiar' => 'Copy',
    'General' => 'General',
    'Limpiar filtros' => 'Clear filters',
    'Nueva Solicitud' => 'New Request',
    'Recargar' => 'Reload',
    'Recargar manteniendo filtros' => 'Reload keeping filters',
    'Teléfono' => 'Phone',
    'Tipo llamada' => 'Call type',
    'grid_reset_filter' => 'grid_reset_filter',
    'Buscar dirección' => 'Find address',
    'Centrar ' => 'Center',
    'Cerrar' => 'Close',
    'Comprobar' => 'Check',
    'Descargar Carta' => 'Download Letter',
    'Descargar Solicitud' => 'Download Request',
    'Descargar excel con todas las solicitudes' => 'Download excel with all requests',
    'Descargar facturas' => 'Download invoices',
    'Editar' => 'Edit',
    'Editar Contrato' => 'Edit Contract',
    'Eliminar' => 'Delete',
    'Eliminar filtros' => 'Remove filters',
    'Enviar' => 'Send',
    'Limpiar' => 'Clear',
    'Ver' => 'See',

];
